In [1]:
import numpy as np 

## 0D Tensors 
- Basically Scalars 

In [2]:
a = np.array(5)
print(a.ndim)
print(a.shape)
print(a)

0
()
5


## 1D Tensors
- Vectors
- Still can have multiple dimensions

In [3]:
a = np.array([1,2,3])
print(a.ndim)
print(a.shape)
print(a)

1
(3,)
[1 2 3]


## 2D Tensors
- Collections of vectors(matrix)
- 2 Dimensional Tensors ( Row and column )

In [5]:
a = np.array([[1,2,3],[3,4,5],[5,3,2]])
print(a.ndim)
print(a.shape)
print(a)

2
(3, 3)
[[1 2 3]
 [3 4 5]
 [5 3 2]]


## 3D Tensors
- Collection of matrices
- 3D(row column depth)

In [7]:
a = np.array([[[1,2,3]],[[2,3,4]]])
print(a.ndim)
print(a.shape)
print(a)

3
(2, 1, 3)
[[[1 2 3]]

 [[2 3 4]]]
